### ISSUE TITLE
Can't compile - Makefile invalid

### ISSUE THREAD

**Issue by johncant** [etola/libdaisy#2]
After following the instructions in the README, I get:

`makefile:420: *** recipe commences before first target.  Stop.`

It seems as thought the makefile is invalid. How can I regenerate said makefile?

**Comment by etola** [comment]
I think it's related with your OS - My guess is you've SUSE ? 

the rule 'export' defined in the makefile sometimes generates this error under SUSE - my recommendation is just to rename the rule from 'export' to 'export-makefile'

cheers

**Comment by johncant** [comment]
Thankyou! That worked! If I added the GNU autotools to build this project, would you accept a pull request?

**Comment by johncant** [comment]
(Arch by the way) - Also, I just tried it on Ubuntu worked fine on Ubuntu 12.10 and it worked fine.

**Comment by ubuntuslave** [comment]
Hello, Engin.

I think you were using  `autoconf` and `automake` to auto-generate the _Makefile_. 
Do you think you could add (to this repo) the missing _configure_ file generated by autoconf?

Thanks in advance!

**Comment by etola** [comment]
I don't use autoconf. the makefile is using the below configuration utility. I used the 'make export_makefile' command to generate the included single makefile. If there's a problem and you want to have a light-weight makefile, call 'make revert' - check the flags,rules,static-variables files of the makefile-heaven - it has some new updates and can resolve the issues you might be having...

https://github.com/etola/makefile-heaven

cheers
